// import React from 'react'; 

// //temperary 'data source' until mapbox active
// export const resourceObjects = [
//     {'name': 'name1',
//     'id': 'id1', 
//     'website': 'website', 
//     'bio': 'bio',
//     'telephone': 'telephone', 
//     'type': 'type1',
//     'coordinates': 'coordinates',
//     'onClick': 'onClick',
//     'className': 'className'},
//     {'name': 'name2',
//     'id': 'id2', 
//     'website': 'website', 
//     'bio': 'bio',
//     'telephone': 'telephone', 
//     'type': 'type2',
//     'coordinates': 'coordinates',
//     'onClick': 'onClick',
//     'className': 'className'},
//    { 'name': 'name3',
//     'id': 'id3', 
//     'website': 'website', 
//     'bio': 'bio',
//     'telephone': 'telephone', 
//     'type': 'type3',
//     'coordinates': 'coordinates',
//     'onClick': 'onClick',
//     'className': 'className'},
//     { 'name': 'name4',
//      'id': 'id3', 
//      'website': 'website', 
//      'bio': 'bio',
//      'telephone': 'telephone', 
//      'type': 'type3',
//      'coordinates': 'coordinates',
//      'onClick': 'onClick',
//      'className': 'className'},
//      { 'name': 'name5',
//       'id': 'id3', 
//       'website': 'website',     
//       'bio': 'bio',
//       'telephone': 'telephone', 
//       'type': 'type3',
//       'coordinates': 'coordinates',
//       'onClick': 'onClick',
//       'className': 'className'},
//       { 'name': 'name6',
//        'id': 'id3', 
//        'website': 'website', 
//        'bio': 'bio',
//        'telephone': 'telephone', 
//        'type': 'type3',
//        'coordinates': 'coordinates',
//        'onClick': 'onClick',
//        'className': 'className'}
// ]; 
